sudo: required
services:
    - docker

before_install:
    - docker build -t sonuajayin/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
    - docker run -e CI=true sonuajayin/react-test npm run test -- --coverage

after_success:
    - docker build -t sonuajayin/multi-client ./complex/client
    - docker build -t sonuajayin/multi-nginx ./complex/nginx
    - docker build -t sonuajayin/multi-server ./complex/server
    - docker build -t sonuajayin/multi-worker ./complex/worker
    # Login to Docker CLI
    # Go to travis settings for the project and add env variables
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push sonuajayin/multi-client
    - docker push sonuajayin/multi-nginx
    - docker push sonuajayin/multi-server
    - docker push sonuajayin/multi-worker