sudo: required
services:
    - docker

before_install:
    - docker build -t sonuajayin/react_frontend -f ./prod_workflow/frontend/Dockerfile.dev

script:
    - docker run sonuajayin/react_frontend npm run test #-- --coverage