version: '3'
services: 
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev        
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
# abpve we have mentioned (line 12). that is current folder
# and for line 11 we are just bookmarking the volume since its already there in the docker workdir
# for windows add environments as below
# services:
#    environment: 
#        - CHOKIDAR_USEPOLLING=true

# test service is separate for testing
# line 21 is to override the command in dockerfile