apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: k8s-ajaykumarsingh-in-tls
spec:
    secretName: k8s-ajaykumarsingh-in
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: ajaykumarsingh.in
    dnsNames:
        - k8s.ajaykumarsingh.in
        - k8s1.ajaykumarsingh.in
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - k8s.ajaykumarsingh.in
                - k8s1.ajaykumarsingh.in